### ISSUE TITLE
Live version of theme is closed

### ISSUE THREAD

**Issue by mcclowes** [zendesk/copenhagen_theme#23]
The readme links to a live version of the theme:
https://copenhagentheme.zendesk.com/hc/en-us) 

This redirects to:
https://www.zendesk.co.uk/help-center-closed/?utm_source=helpcenter-closed&utm_medium=poweredbyzendesk&utm_campaign=text&utm_content=copenhagentheme.zendesk.com

Either the link is wrong or the example help centre has been deactivated?

**Comment by augustocravosilva** [comment]
Hey @mcclowes,
Sorry for the delay here. Thanks for pointing that out.
We have removed that reference from the ReadMe.

This is the theme that is provisioned by default with Guide so we have stoped maintaining that showcase help center.
