### ISSUE TITLE
Missing assets?

### ISSUE THREAD

**Issue by drewbeck** [zendesk/copenhagen_theme#24]
README says about the Assets folder:

> These are the images and font files that are needed for the theme. These includes:
> 
> Default Favicon
> Home page banner image
> Community banner image (for Community topics list page)
> Community image (for Community section in Home page)
> Copenhagen icons font
> Entypo icon font
> Dropdown arrow

Currently the only things in the Assets folder are the dropdown arrow and a loader gif. It looks like it's missing all the rest!

**Comment by augustocravosilva** [comment]
Hey @drewbeck,
Sorry for the delay here.
We have updated the read me to be consistent with what we provide.
