### ISSUE TITLE
Better contact for "Zendesk/Delta"?

### ISSUE THREAD

**Issue by YesThatAllen** [zendesk/copenhagen_theme#61]
In https://github.com/zendesk/copenhagen_theme/commit/19df9c97d781827621254c385125efe96cd7ead7, @augustocravosilva says to mention `zendesk/delta`. 

That group isn't visible to the public. Could we get some updated instructions?

**Comment by jfrancoist** [comment]
Hi @YesThatAllen,

We will update the readme doc. I think that just writing an issue should be fine for now. I think the team is already watching the repo.

Thanks for pointing this out.

**Comment by augustocravosilva** [comment]
Hey @YesThatAllen,
Sorry for the delay here.
We have updated the read me with the correct team name.
