### ISSUE TITLE
Does Zendesk Guide support translation files?

### ISSUE THREAD

**Issue by yoshiaki-natsume** [zendesk/copenhagen_theme#76]
Hello

I forked this repo and made my own theme.
And I changed translations/*.json to change text on Zendesk Guide.
But *.json doesn't affect on Zendesk Guide.(Of course I uploaded my theme and changed it to live)

How can I use my own translation settings?
thank you.

**Comment by ts-1** [comment]
@yoshiaki-natsume where do you want to change the text on Zendesk Guide? Is it in the theme or do you want to translate any text in the settings?

If you want to translate any text in the settings then it is related to translations/*.json or else you need to edit the *.hbs templates to change the text.

**Comment by yoshiaki-natsume** [comment]
@ts-1 thank you for your reply!
I'd like to change `related_articles_label` text in *.json
But when I changed `related_articles_label` text, it doesn't affect article page's text.

>If you want to translate any text in the settings then it is related to translations/*.json or else you need to edit the *.hbs templates to change the text.

Should I need to change `{{related_articles}}` variable or something?
I can't change `related_articles_label` variable directly in article_page.hbs

**Comment by augustocravosilva** [comment]
Sorry for the very late reply here
Theses translations are for the theme settings sidebar (for theme developers to be able to provide their own settings localized to the languages they support).
Zendesk provides custom multilingual snippets that can be used in themes with [Dynamic Content](https://support.zendesk.com/hc/en-us/articles/203663356-Providing-multiple-language-support-with-dynamic-content-Professional-and-Enterprise-)
